New update
WH0SUMIT/propack pull request #41
Opened 2021-07-14 18:30 UTC by Baba-Yaga-1

Fixed #29 

I have added the calculator. Can you check the PR ?

2021-07-16 09:33 UTC, yashsehgal requested changes
Hey @Baba-Yaga-1 👋🏽 
Your code changes look good to me. There are some minor fixes you need to do first, after that I will merge your PR 🚀 

- Firstly, Fetch all the changes from upstream as there are some updates in common modules.
- Then change the `id` in the JSON file from `7` to `8`
- Update your PR with these changes and I will merge it then :D

2021-07-16 10:53 UTC, Baba-Yaga-1 commented
I made the PR 2 days back , maybe that's why conflict happened. And yeah I will fix the issues.

2021-07-16 20:14 UTC, Baba-Yaga-1 commented
I have updated the json file. Can you check it now ?

2021-07-17 10:42 UTC, yashsehgal requested changes
Everything is fine now, Just need to change that ID thing. Please look into it @Baba-Yaga-1

2021-07-17 10:42 UTC, yashsehgal commented on projects/project.json
> +    "id": "7",
@Baba-Yaga-1 Please do change the project ID to `8`

Like `"id": "8"`

2021-07-19 06:31 UTC, Baba-Yaga-1 commented
I updated the id that day itself, so now its showing nothing to commit.

![example1](https://user-images.githubusercontent.com/56999749/126113089-2ef7769a-4eed-40cf-807f-de82a6927674.JPG)

2021-07-19 08:37 UTC, yashsehgal commented
> I updated the id that day itself, so now its showing nothing to commit. What should I do ?
> 
> ![example1](https://user-images.githubusercontent.com/56999749/126113089-2ef7769a-4eed-40cf-807f-de82a6927674.JPG)

Alright, @Baba-Yaga-1 👍🏽 I will merge this as of now, If there will be any such bugs, I will resolve them by myself 👍🏽 

**Good work 💯**

2021-07-19 08:37 UTC, merged